/** Auto-generated by scripts/bake-images.cjs - natural dims of the largest baked variant. */
export const IMAGE_DIMS: Record<string, { w: number; h: number }> = {
  "ajran": {
    "w": 246,
    "h": 317
  },
  "coca-cola": {
    "w": 184,
    "h": 720
  },
  "hamburger-mish-pule": {
    "w": 360,
    "h": 360
  },
  "hamburger-tradicional": {
    "w": 415,
    "h": 350
  },
  "hotdog": {
    "w": 687,
    "h": 395
  },
  "jogurt": {
    "w": 490,
    "h": 621
  },
  "pomfrit": {
    "w": 350,
    "h": 350
  },
  "uje-rugove": {
    "w": 69,
    "h": 217
  }
};
