/** Auto-generated by scripts/bake-images.cjs - natural dims of the largest baked variant. */
export const IMAGE_DIMS: Record<string, { w: number; h: number }> = {
  "ajran": {
    "w": 245,
    "h": 720
  },
  "coca-cola": {
    "w": 205,
    "h": 720
  },
  "fanta": {
    "w": 204,
    "h": 355
  },
  "hamburger-me-qyfte": {
    "w": 410,
    "h": 329
  },
  "hamburger-mish-pule": {
    "w": 478,
    "h": 277
  },
  "hamburger-tradicional": {
    "w": 229,
    "h": 260
  },
  "hotdog": {
    "w": 295,
    "h": 208
  },
  "jogurt": {
    "w": 316,
    "h": 720
  },
  "pomfrit": {
    "w": 720,
    "h": 557
  },
  "tost": {
    "w": 720,
    "h": 355
  },
  "uje-natyral": {
    "w": 240,
    "h": 720
  }
};
