const sharp = require('sharp');
const fs = require('fs');
const path = require('path');
const SRC = '/home/f0id/Downloads/fastfoodfriends/public/menu';
const OUT = path.join(SRC, 'v2');
fs.mkdirSync(OUT, { recursive: true });
const TIERS = [240, 480, 720];
(async () => {
  const files = fs.readdirSync(SRC).filter(f => f.endsWith('.webp'));
  const dims = {};
  let totalAvif = 0, totalWebp = 0, count = 0;
  for (const f of files) {
    const id = f.replace(/\.webp$/, '');
    const src = path.join(SRC, f);
    const meta = await sharp(src).metadata();
    let largest = null;
    for (const tier of TIERS) {
      const buf = await sharp(src)
        .resize(tier, tier, { fit: 'inside', withoutEnlargement: true })
        .toBuffer();
      const m = await sharp(buf).metadata();
      if (!largest || m.width > largest.w) largest = { w: m.width, h: m.height };
      const avif = await sharp(buf).avif({ quality: 70, effort: 4 }).toBuffer();
      const webp = await sharp(buf).webp({ quality: 80, effort: 5 }).toBuffer();
      fs.writeFileSync(path.join(OUT, `${id}-${tier}.avif`), avif);
      fs.writeFileSync(path.join(OUT, `${id}-${tier}.webp`), webp);
      totalAvif += avif.length; totalWebp += webp.length; count += 2;
    }
    dims[id] = largest;
    console.log(`${id}: source ${meta.width}x${meta.height} -> tiers done`);
  }
  fs.writeFileSync('/home/f0id/Downloads/fastfoodfriends/lib/image-dims.ts',
    `/** Auto-generated by scripts/bake-images.cjs - natural dims of the largest baked variant. */\nexport const IMAGE_DIMS: Record<string, { w: number; h: number }> = ${JSON.stringify(dims, null, 2)};\n`);
  console.log(`DONE ${count} files | avif total ${(totalAvif/1024).toFixed(0)}KB | webp total ${(totalWebp/1024).toFixed(0)}KB`);
})().catch(e => { console.error(e); process.exit(1); });
